src/main/java/com/sparta/popupstore/domain/user/controller/UserController.java, src/main/java/com/sparta/popupstore/domain/user/dto/response/UserMypageResponseDto.java, src/main/java/com/sparta/popupstore/domain/user/service/UserService.java
고객 마이페이지 완료
- {userId} url에 담아서 임시진행(회원정보없어서)
- api테스트 완료
=> [#21] feat: 고객 마이페이지 완료

src/main/java/com/sparta/popupstore/config/AuthUserResolver.java, src/main/java/com/sparta/popupstore/config/WebConfig.java, src/main/java/com/sparta/popupstore/domain/common/annotation/AuthUser.java, src/main/java/com/sparta/popupstore/domain/promotionalevent/repository/CouponRepository.java, src/main/java/com/sparta/popupstore/domain/user/controller/UserController.java, src/main/java/com/sparta/popupstore/domain/user/dto/request/UserSigninRequestDto.java, src/main/java/com/sparta/popupstore/domain/user/dto/response/CouponResponseDto.java, src/main/java/com/sparta/popupstore/domain/user/dto/response/UserMyCouponsResponseDto.java, src/main/java/com/sparta/popupstore/domain/user/dto/response/UserSignupResponseDto.java, src/main/java/com/sparta/popupstore/domain/user/repository/UserRepository.java, src/main/java/com/sparta/popupstore/domain/user/service/UserService.java, src/main/java/com/sparta/popupstore/jwt/JwtUtil.java
고객 나의 쿠폰 보기
- {userId} url에 담아서 임시진행(회원정보없어서)
- api테스트 완료
=> [#22] feat: 고객 나의 쿠폰 보기

src/main/java/com/sparta/popupstore/config/AuthCompanyResolver.java, src/main/java/com/sparta/popupstore/domain/common/annotation/AuthCompany.java, src/main/java/com/sparta/popupstore/domain/company/controller/CompanyController.java, src/main/java/com/sparta/popupstore/domain/company/dto/request/CompanySigninRequestDto.java, src/main/java/com/sparta/popupstore/domain/company/repository/CompanyRepository.java, src/main/java/com/sparta/popupstore/domain/company/service/CompanyService.java, src/main/java/com/sparta/popupstore/domain/user/entity/User.java, src/main/java/com/sparta/popupstore/jwt/JwtUtil.java
- 유저 기본 권한 부여
- 회사 로그인 시 쿠키에 토큰 담아서 반환.
- @AuthCompany 어노테이션 사용 시 토큰에서 로그인 정보 반환.
=> [#33] 회사 로그인 및 어노테이션 기능 구현

src/main/java/com/sparta/popupstore/config/AuthCompanyResolver.java, src/main/java/com/sparta/popupstore/config/WebConfig.java, src/main/java/com/sparta/popupstore/domain/company/controller/CompanyController.java, src/main/java/com/sparta/popupstore/domain/company/dto/response/CompanyMyPageResponseDto.java, src/main/java/com/sparta/popupstore/domain/company/service/CompanyService.java
[시나리오]
1. 회사 마이페이지 반환값없었는데 필요한 정보만 반환하는걸로 수정
2. @AuthCompany 일부 수정
=> [#23] feat: 회사 마이페이지 구현

src/main/java/com/sparta/popupstore/domain/promotionevent/controller/PromotionEventController.java, src/main/java/com/sparta/popupstore/domain/promotionevent/dto/response/PromotionEventFindAllPopupStoreResponseDto.java, src/main/java/com/sparta/popupstore/domain/promotionevent/dto/response/PromotionEventFindAllResponseDto.java, src/main/java/com/sparta/popupstore/domain/promotionevent/dto/response/PromotionEventFindOnePopupStoreResponseDto.java, src/main/java/com/sparta/popupstore/domain/promotionevent/dto/response/PromotionEventFindOneResponseDto.java, src/main/java/com/sparta/popupstore/domain/promotionevent/service/PromotionEventService.java
```json
{
"id": 3,
"title": "선착순 1천명 할인 쿠폰 이벤트",
"description": "할인 쿠폰 받아가세요 ~ ",
"promotionEventFindPopupStoreResponseDto": {
"id": 3,
"name": null,
"image": null,
"price": 1123123,
"startDate": null,
"endDate": null,
"startTime": null,
"endTime": null
},
"discountPercentage": 50,
"totalCount": 1000,
"startDateTime": null,
"endDateTime": null
}
```
```json
{
"id": 18,
"title": "선착순 1천명 할인 쿠폰 이벤트",
"description": "할인 쿠폰 받아가세요 ~ ",
"promotionEventFindPopupStoreResponseDto": null,
"discountPercentage": 50,
"totalCount": 1000,
"startDateTime": "2024-12-01T20:00:00",
"endDateTime": "2024-12-04T22:00:00"
}
```
=> [#15] feat : 이벤트 단건조회 기능 구현

src/main/java/com/sparta/popupstore/domain/company/controller/CompanyController.java, src/main/java/com/sparta/popupstore/domain/company/dto/response/CompanyMyPopupStoreResponseDto.java, src/main/java/com/sparta/popupstore/domain/company/service/CompanyService.java, src/main/java/com/sparta/popupstore/domain/popupstore/repository/PopupStoreRepository.java
=> [#24] feat: 회사 자사 팝업스토어 조회

src/main/java/com/sparta/popupstore/domain/company/repository/CompanyRepository.java, src/main/java/com/sparta/popupstore/domain/company/service/CompanyService.java, src/main/java/com/sparta/popupstore/domain/popupstore/controller/PopupStoreController.java, src/main/java/com/sparta/popupstore/domain/popupstore/dto/request/PopupStoreCreateRequestDto.java, src/main/java/com/sparta/popupstore/domain/popupstore/dto/request/PopupStoreSaveRequestDto.java, src/main/java/com/sparta/popupstore/domain/popupstore/dto/response/PopupStoreCreateResponseDto.java, src/main/java/com/sparta/popupstore/domain/popupstore/dto/response/PopupStoreSaveResponseDto.java, src/main/java/com/sparta/popupstore/domain/popupstore/entity/PopupStore.java, src/main/java/com/sparta/popupstore/domain/popupstore/service/PopupStoreService.java
=> [#17] 팝업스토어 생성 기능 추가

src/main/java/com/sparta/popupstore/domain/common/annotation/StartAndDateTimeCheck.java, src/main/java/com/sparta/popupstore/domain/common/validation/StartAndDateTimeCheckValidation.java, src/main/java/com/sparta/popupstore/domain/promotionevent/service/PromotionEventService.java
또한 시작일을 현재 시간보다 최소 24시간 이후로만 설정할 수 있도록 수정
=> [#13] fix : 이미 시작된 이벤트는 수정이 불가능 하도록 수정

src/main/java/com/sparta/popupstore/domain/common/validation/StartAndDateTimeCheckValidation.java, src/main/java/com/sparta/popupstore/domain/promotionevent/service/PromotionEventService.java
=> [#14] fix : 이벤트 삭제 요청 시 이미 시작된 이벤트면 예외던지도록 수정

src/main/java/com/sparta/popupstore/domain/common/validation/StartAndDateTimeCheckValidation.java, src/main/java/com/sparta/popupstore/domain/promotionevent/dto/response/CouponCreateResponseDto.java, src/main/java/com/sparta/popupstore/domain/promotionevent/entity/Coupon.java
```json
{
"id": 2,
"serialNumber": "2fc16a67-63f2-4d8c-bbb7-4376b63cee6f",
"userName": "승승",
"popupStoreName": "눈사람",
"couponExpirationPeriod": "2025-01-04T10:46:53.5511965"
}
```
=> [#46] fix : 쿠폰 발급 시 만료기간도 같이 넣어주도록 수정

src/main/java/com/sparta/popupstore/domain/popupstore/controller/PopupStoreController.java, src/main/java/com/sparta/popupstore/domain/popupstore/dto/request/PopupStoreUpdateRequestDto.java, src/main/java/com/sparta/popupstore/domain/popupstore/dto/response/PopupStoreUpdateResponseDto.java, src/main/java/com/sparta/popupstore/domain/popupstore/entity/PopupStore.java, src/main/java/com/sparta/popupstore/domain/popupstore/service/PopupStoreService.java
=> [#18]  팝업스토어 수정 기능 구현

src/main/java/com/sparta/popupstore/domain/popupstore/controller/PopupStoreController.java, src/main/java/com/sparta/popupstore/domain/popupstore/dto/response/PopupStoreFindOneResponseDto.java, src/main/java/com/sparta/popupstore/domain/popupstore/service/PopupStoreService.java
=> [#19] 팝업스토어 단건 조회 기능 구현

src/main/java/com/sparta/popupstore/config/AuthUserResolver.java, src/main/java/com/sparta/popupstore/config/CheckRoleInterceptor.java, src/main/java/com/sparta/popupstore/config/WebConfig.java, src/main/java/com/sparta/popupstore/domain/common/annotation/CheckAdmin.java, src/main/java/com/sparta/popupstore/domain/common/exception/ErrorCode.java, src/main/java/com/sparta/popupstore/domain/popupstore/controller/PopupStoreController.java, src/main/java/com/sparta/popupstore/domain/popupstore/service/PopupStoreService.java, src/main/java/com/sparta/popupstore/domain/promotionevent/controller/PromotionEventController.java, src/main/java/com/sparta/popupstore/domain/user/controller/UserController.java, src/main/java/com/sparta/popupstore/domain/user/dto/request/UserSignupRequestDto.java, src/main/java/com/sparta/popupstore/domain/user/dto/response/UserSignupResponseDto.java, src/main/java/com/sparta/popupstore/domain/user/dto/response/UserUpdateResponseDto.java, src/main/java/com/sparta/popupstore/domain/user/entity/User.java, src/main/java/com/sparta/popupstore/jwt/JwtUtil.java
1. CheckAdmin 어노테이션으로 손쉽게 유저 권한 확인 가능.
2. userResponseDto가 password 반환하지 않도록 수정.
3. userRole의 기본값 수정.
4. Admin 확인하는 로직들 수정
=> [#62] 유저 권한 확인 인터셉터 구현

src/main/java/com/sparta/popupstore/PopupStoreApplication.java, src/main/java/com/sparta/popupstore/domain/promotionevent/entity/Coupon.java, src/main/java/com/sparta/popupstore/domain/promotionevent/entity/CouponStatus.java, src/main/java/com/sparta/popupstore/domain/promotionevent/repository/CouponRepository.java, src/main/java/com/sparta/popupstore/domain/promotionevent/repository/PromotionEventRepository.java, src/main/java/com/sparta/popupstore/domain/promotionevent/scheduler/PromotionEventEndCouponDeleteScheduler.java, src/main/java/com/sparta/popupstore/domain/promotionevent/service/CouponService.java
쿠폰 softDelete 와 이벤트 soft & hardDelete 스케줄러 구현
쿠폰 StatusEnum 생성해서  발급, 사용, 만료 관리
=> [#77] feat : 쿠폰과 이벤트 삭제 스케줄러 구현

build.gradle, src/main/java/com/sparta/popupstore/config/S3config.java, src/main/java/com/sparta/popupstore/domain/common/exception/ErrorCode.java, src/main/java/com/sparta/popupstore/domain/review/controller/ReviewController.java, src/main/java/com/sparta/popupstore/domain/review/dto/request/ReviewCreateRequestDto.java, src/main/java/com/sparta/popupstore/domain/review/dto/response/ReviewCreateResponseDto.java, src/main/java/com/sparta/popupstore/domain/review/entity/Review.java, src/main/java/com/sparta/popupstore/s3/S3ImageController.java, src/main/java/com/sparta/popupstore/s3/S3ImageService.java, src/main/java/com/sparta/popupstore/s3/dto/request/ReviewImageRequestDto.java, src/main/java/com/sparta/popupstore/s3/dto/response/S3UrlResponseDto.java
aws preSignedUrl 사용으로 이미지 업로드 요청 시 preSignedUrl 발급 후 해당 경로로 Put 요청 시 aws 버킷에 이미지 저장 
`GET` /reviews/preassigned
```json
{
"fileName" : "허니콤보.png"
}
```
```json
{
"star" : 2,
"contetns" : "재미",
"imageUrl" : "https://dsadw.s3.ap-northeast-2.amazonaws.com/review/9b3e71a5-6796-4cbf-9e2c-153584a93f59허니콤보.png"
}
```
=> [#81] refactor : 리뷰 등록 시 이미지 업로드 기능 추가

src/main/java/com/sparta/popupstore/domain/promotionevent/dto/request/PromotionEventCreateRequestDto.java, src/main/java/com/sparta/popupstore/domain/promotionevent/dto/response/PromotionEventCreateResponseDto.java, src/main/java/com/sparta/popupstore/domain/promotionevent/entity/PromotionEvent.java, src/main/java/com/sparta/popupstore/s3/S3ImageController.java, src/main/java/com/sparta/popupstore/s3/S3ImageService.java, src/main/java/com/sparta/popupstore/s3/dto/request/ImageRequestDto.java
=> [#82] refactor : 프로모션 이벤트 추가 할 때 이미지 업로드 기능 추가

src/main/java/com/sparta/popupstore/domain/popupstore/controller/PopupStoreController.java, src/main/java/com/sparta/popupstore/domain/popupstore/dto/request/PopupStoreCreateRequestDto.java, src/main/java/com/sparta/popupstore/domain/popupstore/dto/request/PopupStoreImageRequestDto.java, src/main/java/com/sparta/popupstore/domain/popupstore/entity/PopupStore.java, src/main/java/com/sparta/popupstore/domain/popupstore/entity/PopupStoreImage.java, src/main/java/com/sparta/popupstore/domain/popupstore/service/PopupStoreService.java, src/main/java/com/sparta/popupstore/s3/S3ImageController.java, src/main/java/com/sparta/popupstore/s3/S3ImageService.java
팝업스토어 생성시에는 이미지가 필수로 들어가야한다.
Url 얻는 Request
```json
[
{
"fileName" : "콤보.png"
},
{
"fileName" : "와다다.png"
}
]
```
팝업등록 Request
```json
{
"name" : "탕탕후룩",
"content" : "이빨 후루룩",
"price" : 1000,
"address" : "광명ㅇㅇ영",
"startDate" : "2024-12-13",
"endDate" : "2024-12-14",
"startTime" : "20:00:00",
"endTime" : "21:00:00",
"images" : 
[
{
"imageUrl" : "http:~~",
"sort" : 0
}
{
"imageUrl" : "http:~~",
"sort" : 1 
}
]
}
```
=> [#83] refactor : 팝업스토어 생성 시 이미지 업로드 구현 가능

src/main/java/com/sparta/popupstore/domain/common/exception/ErrorCode.java, src/main/java/com/sparta/popupstore/s3/S3ImageController.java, src/main/java/com/sparta/popupstore/s3/S3ImageService.java
=> [#104] feat : s3 이미지 삭제 기능 구현

src/main/java/com/sparta/popupstore/domain/common/exception/ErrorCode.java, src/main/java/com/sparta/popupstore/domain/popupstore/controller/PopupStoreController.java, src/main/java/com/sparta/popupstore/domain/popupstore/dto/request/PopupStoreCreateRequestDto.java, src/main/java/com/sparta/popupstore/domain/popupstore/dto/response/PopupStoreFindOneResponseDto.java, src/main/java/com/sparta/popupstore/domain/popupstore/entity/PopupStore.java, src/main/java/com/sparta/popupstore/domain/popupstore/service/PopupStoreService.java, src/main/java/com/sparta/popupstore/domain/review/service/ReviewService.java, src/main/java/com/sparta/popupstore/web/WebUtil.java
회원일 경우 쿠키를 생성하여 새로 고침 시 조회수가 무한하게 증가하는 것을 방지
=> [#98] 로그인한 유저가 단건 조회시 조회수 증가 기능 구현

src/main/java/com/sparta/popupstore/domain/common/util/IsValidNullAndEmpty.java, src/main/java/com/sparta/popupstore/domain/common/util/ValidUtil.java, src/main/java/com/sparta/popupstore/domain/promotionevent/controller/PromotionEventController.java, src/main/java/com/sparta/popupstore/domain/promotionevent/dto/request/PromotionEventUpdateRequestDto.java, src/main/java/com/sparta/popupstore/domain/promotionevent/entity/PromotionEvent.java, src/main/java/com/sparta/popupstore/domain/promotionevent/service/PromotionEventService.java, src/main/java/com/sparta/popupstore/domain/review/service/ReviewService.java
반복되는 null 체크와 isEmpty() 를 util 클래스를 하나 만들어서 스태틱 메서드로 만들어서 사용하도록 했습니다. IsValidNullAndEmpty.isValidNullAndEmpty(promotionEvent.getImageUrl()) 이런식으로 사용하시면됩니다 !
=> [#110] refactor : 이벤트 수정 시 이미지도 수정 가능하도록 변경

src/main/java/com/sparta/popupstore/domain/common/exception/ErrorCode.java, src/main/java/com/sparta/popupstore/domain/oauth2/client/common/OAuth2Client.java, src/main/java/com/sparta/popupstore/domain/oauth2/client/common/TokenResponse.java, src/main/java/com/sparta/popupstore/domain/oauth2/client/google/GoogleOAuth2Client.java, src/main/java/com/sparta/popupstore/domain/oauth2/client/google/dto/GoogleTokenResponse.java, src/main/java/com/sparta/popupstore/domain/oauth2/client/google/dto/GoogleUserInfoResponse.java, src/main/java/com/sparta/popupstore/domain/oauth2/client/kakao/KakaoOAuth2Client.java, src/main/java/com/sparta/popupstore/domain/oauth2/controller/OAuth2SigninController.java, src/main/java/com/sparta/popupstore/domain/oauth2/service/OAuth2SigninService.java, src/main/java/com/sparta/popupstore/domain/oauth2/service/SocialUserService.java, src/main/java/com/sparta/popupstore/domain/oauth2/type/OAuth2Provider.java
=> [#72] 구글 소셜 로그인 기능 구현

src/main/java/com/sparta/popupstore/domain/company/dto/response/CompanyMyPageResponseDto.java, src/main/java/com/sparta/popupstore/domain/popupstore/controller/PopupStoreController.java, src/main/java/com/sparta/popupstore/domain/popupstore/dto/response/PopupStoreCreateResponseDto.java, src/main/java/com/sparta/popupstore/domain/popupstore/dto/response/PopupStoreFindOneResponseDto.java, src/main/java/com/sparta/popupstore/domain/popupstore/dto/response/PopupStoreImageResponseDto.java, src/main/java/com/sparta/popupstore/domain/popupstore/dto/response/PopupStoreUpdateResponseDto.java, src/main/java/com/sparta/popupstore/domain/popupstore/service/PopupStoreService.java, src/main/java/com/sparta/popupstore/domain/promotionevent/dto/response/CouponCreateResponseDto.java, src/main/java/com/sparta/popupstore/domain/promotionevent/dto/response/PromotionEventFindAllPopupStoreResponseDto.java, src/main/java/com/sparta/popupstore/domain/promotionevent/dto/response/PromotionEventFindAllResponseDto.java, src/main/java/com/sparta/popupstore/domain/promotionevent/dto/response/PromotionEventFindOnePopupStoreResponseDto.java, src/main/java/com/sparta/popupstore/domain/promotionevent/dto/response/PromotionEventFindOneResponseDto.java, src/main/java/com/sparta/popupstore/domain/promotionevent/dto/response/PromotionEventUpdateResponseDto.java, src/main/java/com/sparta/popupstore/domain/promotionevent/scheduler/PromotionEventEndCouponDeleteScheduler.java, src/main/java/com/sparta/popupstore/domain/promotionevent/service/PromotionEventService.java, src/main/java/com/sparta/popupstore/domain/review/dto/response/ReviewFindAllResponseDto.java, src/main/java/com/sparta/popupstore/domain/review/dto/response/ReviewUpdateResponseDto.java, src/main/java/com/sparta/popupstore/domain/review/service/ReviewService.java, src/main/java/com/sparta/popupstore/domain/user/dto/response/UserMyCouponsResponseDto.java, src/main/java/com/sparta/popupstore/domain/user/dto/response/UserMyPageResponseDto.java, src/main/java/com/sparta/popupstore/domain/user/dto/response/UserSignupResponseDto.java, src/main/java/com/sparta/popupstore/domain/user/dto/response/UserUpdateResponseDto.java, src/main/java/com/sparta/popupstore/s3/controller/S3ImageController.java, src/main/java/com/sparta/popupstore/s3/dto/response/S3UrlResponseDto.java, src/main/java/com/sparta/popupstore/s3/service/S3ImageService.java
S3Controller 와 PopupStoreController 에 swagger 추가
ResponseDto 에 이미지 정보도 넘겨가도록 수정
dto들에도 schema 달아줬습니다.
=> [#126] fix : 회사 - 팝업스토어 삭제 시 s3에 저장된 이미지도 삭제되도록 수정

src/main/java/com/sparta/popupstore/domain/oauth2/client/common/OAuth2Client.java, src/main/java/com/sparta/popupstore/domain/oauth2/client/google/GoogleOAuth2Client.java, src/main/java/com/sparta/popupstore/domain/oauth2/client/kakao/KakaoOAuth2Client.java, src/main/java/com/sparta/popupstore/domain/oauth2/client/kakao/dto/KakaoUserInfoResponse.java, src/main/java/com/sparta/popupstore/domain/oauth2/client/naver/NaverOAuth2Client.java, src/main/java/com/sparta/popupstore/domain/oauth2/client/naver/dto/NaverUserInfoResponse.java, src/main/java/com/sparta/popupstore/domain/oauth2/client/naver/dto/NaverUserResponse.java, src/main/java/com/sparta/popupstore/domain/oauth2/controller/OAuth2SigninController.java, src/main/java/com/sparta/popupstore/domain/oauth2/service/OAuth2SigninService.java, src/main/java/com/sparta/popupstore/domain/oauth2/type/OAuth2Provider.java
네이버는 이메일을 받아올 수 없으며 이름, 닉네임, 전화번호 등을 받아옵니다.
현재는 이름을 이메일로 취급하고 회원가입 하도록 하고 있습니다.
차후 우리 서버의 유저와의 연동을 한다면 고려할 부분이 있을 것 같습니다.
=> [#73] 네이버 소셜 로그인 기능 구현

src/main/java/com/sparta/popupstore/domain/common/exception/ErrorCode.java, src/main/java/com/sparta/popupstore/domain/popupstore/controller/PopupStoreController.java, src/main/java/com/sparta/popupstore/domain/popupstore/dto/request/PopupStoreCreateRequestDto.java, src/main/java/com/sparta/popupstore/domain/popupstore/dto/request/PopupStoreUpdateRequestDto.java, src/main/java/com/sparta/popupstore/domain/popupstore/dto/response/PopupStoreCreateResponseDto.java, src/main/java/com/sparta/popupstore/domain/popupstore/dto/response/PopupStoreFindOneResponseDto.java, src/main/java/com/sparta/popupstore/domain/popupstore/dto/response/PopupStoreUpdateResponseDto.java, src/main/java/com/sparta/popupstore/domain/popupstore/entity/PopupStore.java, src/main/java/com/sparta/popupstore/domain/popupstore/entity/PopupStoreOperating.java, src/main/java/com/sparta/popupstore/domain/popupstore/repository/PopupStoreOperatingRepository.java, src/main/java/com/sparta/popupstore/domain/popupstore/service/PopupStoreOperatingService.java, src/main/java/com/sparta/popupstore/domain/popupstore/service/PopupStoreService.java, src/main/java/com/sparta/popupstore/web/WebUtil.java
1. 팝업스토어 추가 시 운영시간 추가
2. 팝업스토어 수정 시 운영시간 수정
3. 팝업스토어 삭제 시 해당 팝업스토어와 연관된 운영시간 삭제
=> [#97] 팝업스토어 추가 시 운영시간 추가

src/main/resources/static/oAuth2CallbackPhoneNumber.html
[시나리오]
- 소셜로그인 시 클라이언트가 직접 전화번호를 입력하여 데이터베이스에 저장
- 저장된 핸드폰번호로 이미 가입한 회원인지 체크하여 중복가입 확인
[기타 전달사항]
- oAuth2CallbackPhoneNumber 경로와 파일명 통일
- 일반 회원가입(spoton)에서 전화번호 항목 추가되어야함!
=> [#133] feat: 소셜로그인 전화번호 저장

src/main/java/com/sparta/popupstore/domain/common/entity/Address.java, src/main/java/com/sparta/popupstore/domain/popupstore/service/PopupStoreService.java, src/main/java/com/sparta/popupstore/domain/user/controller/UserController.java, src/main/java/com/sparta/popupstore/domain/user/dto/response/UserMyPageResponseDto.java, src/main/java/com/sparta/popupstore/domain/user/entity/User.java, src/main/java/com/sparta/popupstore/domain/user/service/UserService.java, src/main/resources/static/mypage.html
[시나리오]
- 마이페이지 api 호출해서 주소 활용
- 회원가입시 위도 경도 저장
- 더미데이터로 진행
- 팝업스토어 목록 함께 출력
- 쿠키 값은 추후(현재 프론트 로그인도 없고 쿠키가져올방법이없음)
=> [#69] feat: 고객 주소 위,경도 및 지도 연동

build.gradle, src/main/java/com/sparta/popupstore/domain/common/exception/ErrorCode.java, src/main/java/com/sparta/popupstore/domain/promotionevent/controller/PromotionEventController.java, src/main/java/com/sparta/popupstore/domain/reservation/repository/ReservationRepository.java, src/main/java/com/sparta/popupstore/domain/user/controller/QRController.java, src/main/java/com/sparta/popupstore/domain/user/dto/request/UserSignupRequestDto.java, src/main/java/com/sparta/popupstore/domain/user/dto/request/UserValidReservationRequestDto.java, src/main/java/com/sparta/popupstore/domain/user/entity/User.java, src/main/java/com/sparta/popupstore/domain/user/repository/UserRepository.java, src/main/java/com/sparta/popupstore/domain/user/service/QRService.java, src/main/java/com/sparta/popupstore/domain/user/service/UserService.java
- 고객 회원가입 시 고유 번호 생성
- 해당 고유 번호로 qr 생성
- 예약한 시간 30분 전후라면 예외 처리
=> [#80] qr 코드 생성 및 인식 기능 구현

src/main/java/com/sparta/popupstore/domain/common/exception/ErrorCode.java, src/main/java/com/sparta/popupstore/domain/point/service/PointService.java, src/main/java/com/sparta/popupstore/domain/reservation/controller/ReservationController.java, src/main/java/com/sparta/popupstore/domain/reservation/dto/request/ReservationCreateRequestDto.java, src/main/java/com/sparta/popupstore/domain/reservation/dto/response/ReservationCreateResponseDto.java, src/main/java/com/sparta/popupstore/domain/reservation/entity/Reservation.java, src/main/java/com/sparta/popupstore/domain/reservation/service/ReservationService.java, src/main/java/com/sparta/popupstore/domain/user/entity/User.java
1. 유저만 팝업스토어를 예약 할 수 있다.
2. 유저가 아닌경우 -> `403 Fobbiden 에러 발생`
3. 유저의 포인트와 팝업스토어의 입장료를 비교해서 입장권을 결제한다.
4. 유저의 포인트가 부족한 경우 -> `오류발생 오류코드 고민중...`
- 팝업스토어 예약하려면 총 몇팀을 받을지도 생각해야하지 않나요? (ex. 09:00에 최대 예약 가능 팀 5팀)
=> [#94] 팝업스토어 예약 추가

src/main/resources/static/admin/login.html
=> [#155] feat: 관리자 로그인 페이지 

src/main/resources/static/dashboard.html
=> [#156] feat: 관리자 메인페이지(대시보드)

src/main/java/com/sparta/popupstore/domain/popupstore/controller/PopupStoreController.java, src/main/java/com/sparta/popupstore/domain/popupstore/controller/converter/PopupStoreSearchTypeConverter.java, src/main/java/com/sparta/popupstore/domain/popupstore/repository/PopupStoreQueryDslImpl.java, src/main/java/com/sparta/popupstore/domain/popupstore/searchtype/SearchStandard.java, src/main/java/com/sparta/popupstore/domain/popupstore/service/PopupStoreService.java
enum 으로 url 에 이번달 조회면 this-month 이런식으로 보내면 이번달 팝업 조회하는식은 어떨까해서 일단 추가해봤습니다.
=> [#140] fix : queryDsl fetchJoin 추가

src/main/java/com/sparta/popupstore/domain/common/exception/ErrorCode.java, src/main/java/com/sparta/popupstore/domain/reservation/controller/ReservationController.java, src/main/java/com/sparta/popupstore/domain/reservation/repository/ReservationRepository.java, src/main/java/com/sparta/popupstore/domain/reservation/service/ReservationService.java
1. 유저는 자신이 예약한 팝업스토어만 예약 취소 할 수 있다.
2. 예약 내역이 없을 경우 &rarr; `404 Not Found`
3. 자신이 예약한 팝업 스토어가 아닐 경우 &rarr; `403 Forbidden`
=> [#95] 팝업스토어 예약 취소

src/main/resources/static/admin/login.html, src/main/resources/static/css/popup.css, src/main/resources/static/dashboard.html, src/main/resources/static/qrcode.html
=> [#176] fix: css 수정

src/main/resources/static/admin/event.html, src/main/resources/static/admin/reservation.html
- 백엔드 추후 연동
- css는 176번 issue에서 적용
=> [#173] feat: 팝업스토어 예약 내역,  이벤트 목록

src/main/resources/static/admin/company.html, src/main/resources/static/admin/user.html
- 백엔드 추후 연동 
- css는 176번 issue에서 적용
=> [#172] feat: 회사,회원 목록

src/main/resources/static/admin/pointchargelog.html, src/main/resources/static/admin/pointuselog.html
- 백엔드 추후 연동
- css는 176번 issue에서 적용
=> [#174] feat: 포인트 충전 및 사용 내역

src/main/java/com/sparta/popupstore/config/CheckAdminInterceptor.java, src/main/java/com/sparta/popupstore/domain/admin/controller/AdminController.java, src/main/java/com/sparta/popupstore/domain/admin/dto/request/AdminSigninRequestDto.java, src/main/java/com/sparta/popupstore/domain/admin/dto/request/AdminSignupRequestDto.java, src/main/java/com/sparta/popupstore/domain/admin/dto/response/AdminSignupResponseDto.java, src/main/java/com/sparta/popupstore/domain/admin/entity/Admin.java, src/main/java/com/sparta/popupstore/domain/admin/repository/AdminRepository.java, src/main/java/com/sparta/popupstore/domain/admin/service/AdminService.java, src/main/java/com/sparta/popupstore/domain/admin/type/AdminRole.java, src/main/java/com/sparta/popupstore/domain/popupstore/controller/PopupStoreController.java, src/main/java/com/sparta/popupstore/domain/promotionevent/controller/PromotionEventController.java, src/main/java/com/sparta/popupstore/domain/reservation/service/ReservationService.java, src/main/java/com/sparta/popupstore/domain/user/controller/UserController.java, src/main/java/com/sparta/popupstore/domain/user/dto/request/UserSignupRequestDto.java, src/main/java/com/sparta/popupstore/domain/user/entity/User.java, src/main/java/com/sparta/popupstore/domain/user/entity/UserRole.java, src/main/java/com/sparta/popupstore/jwt/JwtUtil.java
일단은 간단하게 controller에 있는 api만 옮긴 수준입니다.
추가된 기능은 관리자 회원 가입과 로그인 입니다.
=> [#151] 일반 유저와 관리자 분리

src/main/java/com/sparta/popupstore/domain/popupstore/controller/PopupStoreController.java, src/main/java/com/sparta/popupstore/domain/popupstore/repository/PopupStoreQueryDsl.java, src/main/java/com/sparta/popupstore/domain/popupstore/repository/PopupStoreQueryDslImpl.java, src/main/java/com/sparta/popupstore/domain/popupstore/service/PopupStoreService.java
=> [#196] feat : 이번달 팝업스토어 조회기능 추가

src/main/java/com/sparta/popupstore/domain/common/exception/ErrorCode.java, src/main/java/com/sparta/popupstore/domain/coupon/entity/Coupon.java, src/main/java/com/sparta/popupstore/domain/coupon/repository/CouponRepository.java, src/main/java/com/sparta/popupstore/domain/coupon/service/CouponService.java, src/main/java/com/sparta/popupstore/domain/point/controller/PointController.java, src/main/java/com/sparta/popupstore/domain/point/dto/request/PointChargeRequestDto.java, src/main/java/com/sparta/popupstore/domain/point/dto/request/PointUseRequestDto.java, src/main/java/com/sparta/popupstore/domain/point/dto/response/PointChargeResponseDto.java, src/main/java/com/sparta/popupstore/domain/point/dto/response/PointChargedLogResponseDto.java, src/main/java/com/sparta/popupstore/domain/point/dto/response/PointUseResponseDto.java, src/main/java/com/sparta/popupstore/domain/point/dto/response/PointUsedLogResponseDto.java, src/main/java/com/sparta/popupstore/domain/point/entity/PointChargedLog.java, src/main/java/com/sparta/popupstore/domain/point/entity/PointUsedLog.java, src/main/java/com/sparta/popupstore/domain/point/service/PointService.java, src/main/java/com/sparta/popupstore/domain/popupstore/bundle/repository/PopupStoreAttributeRepository.java, src/main/java/com/sparta/popupstore/domain/popupstore/dto/request/PopupStoreCreateRequestDto.java, src/main/java/com/sparta/popupstore/domain/popupstore/dto/request/PopupStoreUpdateRequestDto.java, src/main/java/com/sparta/popupstore/domain/popupstore/dto/response/PopupStoreCreateResponseDto.java, src/main/java/com/sparta/popupstore/domain/popupstore/dto/response/PopupStoreGetOneResponseDto.java, src/main/java/com/sparta/popupstore/domain/popupstore/dto/response/PopupStoreSearchResponseDto.java, src/main/java/com/sparta/popupstore/domain/popupstore/dto/response/PopupStoreUpdateResponseDto.java, src/main/java/com/sparta/popupstore/domain/popupstore/entity/PopupStore.java, src/main/java/com/sparta/popupstore/domain/popupstore/service/PopupStoreService.java, src/main/java/com/sparta/popupstore/domain/reservation/controller/ReservationController.java, src/main/java/com/sparta/popupstore/domain/reservation/dto/request/ReservationCreateRequestDto.java, src/main/java/com/sparta/popupstore/domain/reservation/dto/response/ReservationCreateResponseDto.java, src/main/java/com/sparta/popupstore/domain/reservation/entity/Reservation.java, src/main/java/com/sparta/popupstore/domain/reservation/repository/ReservationRepository.java, src/main/java/com/sparta/popupstore/domain/reservation/service/ReservationService.java, src/main/java/com/sparta/popupstore/domain/user/entity/User.java
포인트를 이용하다보니 `pointService`도 수정하게 되었습니다.
---
**변경된 점**
1. 쿠폰에 할인률 column 추가.
2. 기존의 포인트 사용 api 주석 처리
3. 포인트 충전 로그에서 serialNumber 제거
4. 팝업스토어에 예약 가능한 인원 수 column 추가
---
**구현한 기능**
1. 예약 시 인원 수 `number` 추가 입력
2. 현재 시간대에 예약한 인원 수 계산
3. 예약 가능 인원수와 비교하여 예약 가능 여부 판단.
4. 예약 시 포인트 소비
=> [#199] 예약 시 인원 추가

.github/workflows/gradle.yml, src/test/java/com/sparta/popupstore/PopupStoreApplicationTests.java, src/test/java/com/sparta/popupstore/domain/coupon/service/CouponServiceTest.java, src/test/java/com/sparta/popupstore/domain/promotionevent/service/PromotionEventServiceTest.java
- docker-compose 설정 추가
- commit,pr 조건 변경
- 데이터베이스 env 설정
- 테스트코드 주석 제거
=> [#228] refactor: gradle.yml 수정 및 기타 수정

docker-compose.yml, loki/loki-config.yml, promtail/promtail-config.yml
Grafana  explore에서 로그 모니터링가능합니다.
=> [#231] feat : 로그 모니터링 

src/main/java/com/sparta/popupstore/domain/common/exception/ErrorCode.java, src/main/java/com/sparta/popupstore/domain/popupstore/bundle/repository/PopupStoreOperatingRepository.java, src/main/java/com/sparta/popupstore/domain/popupstore/bundle/service/PopupStoreBundleService.java, src/main/java/com/sparta/popupstore/domain/reservation/dto/request/ReservationCreateRequestDto.java, src/main/java/com/sparta/popupstore/domain/reservation/dto/response/ReservationCreateResponseDto.java, src/main/java/com/sparta/popupstore/domain/reservation/entity/Reservation.java, src/main/java/com/sparta/popupstore/domain/reservation/repository/ReservationRepository.java, src/main/java/com/sparta/popupstore/domain/reservation/service/ReservationService.java, src/main/java/com/sparta/popupstore/domain/user/service/QRService.java
1. 예약 시 날짜와 시간을 입력하도록 변경.
2. 일부 검증 로직을 popupStoreBundleService로 이동.
=> [#238] 팝업스토어 예약 수정

src/main/java/com/sparta/popupstore/domain/common/exception/ErrorCode.java, src/main/java/com/sparta/popupstore/domain/promotionevent/dto/request/PromotionEventUpdateRequestDto.java, src/main/java/com/sparta/popupstore/domain/promotionevent/repository/PromotionEventRepository.java, src/main/java/com/sparta/popupstore/domain/promotionevent/scheduler/PromotionEventEndCouponDeleteScheduler.java, src/main/java/com/sparta/popupstore/domain/promotionevent/service/PromotionEventService.java, src/test/java/com/sparta/popupstore/domain/promotionevent/service/PromotionEventServiceTest.java
프로모션 이벤트 서비스 테스트 코드 추가 및 프로모션 이벤트 서비스 일부 코드 수정과 스케줄러 메서드 명 변경
=> [#235] feat : 프로모션 이벤트  테스트코드

src/main/java/com/sparta/popupstore/domain/reservation/dto/request/ReservationCreateRequestDto.java, src/test/java/com/sparta/popupstore/domain/reservation/service/ReservationServiceTest.java
**시나리오**
10명이 예약 가능한 팝업스토어에
1. 5명이 예약 시 성공.
2. 20명이 예약 시 인원 초과
3. 5명이 예약한 상태에서 8명이 예약 시 인원 초과
=> [#237] 인원수 별 예약 테스트

build.gradle, src/main/java/com/sparta/popupstore/domain/promotionevent/scheduler/PromotionEventEndCouponDeleteScheduler.java, src/main/java/com/sparta/popupstore/s3/controller/S3ImageController.java, src/main/java/com/sparta/popupstore/s3/scheduler/S3Scheduler.java, src/main/java/com/sparta/popupstore/s3/service/S3ImageService.java
리뷰 - 매일 새벽 1시
프로모션 이벤트 - 매일 새벽 2시 30분
팝업스토어 - 매일 새벽 4시
마다 스케줄러가 돌아갑니다.
데이터가 늘어날수록 작업시간이 많이 걸릴 수도 있을 것 같아서 1시간 반 간격으로 해뒀습니다.
=> [#249] feat : 쓰이지 않는 이미지 s3에서 삭제하는 스케줄러

Dockerfile, src/main/java/com/sparta/popupstore/domain/popupstore/bundle/dto/request/PopupStoreAttributeRequestDto.java, src/main/java/com/sparta/popupstore/domain/popupstore/bundle/dto/request/PopupStoreOperatingRequestDto.java, src/main/java/com/sparta/popupstore/domain/popupstore/dto/request/PopupStoreUpdateRequestDto.java, src/test/java/com/sparta/popupstore/domain/popupstore/service/PopupstoreServiceTest.java
1. 성공
2. 존재하지 않는 팝업스토어
3. 다른 회사가 소유한 팝업스토어
=> [#247] 팝업스토어 수정 테스트 코드

.github/workflows/gradle.yml, loki/loki-config.yml, promtail/promtail-config.yml, src/main/resources/logback-spring.xml
ci actions 브랜치 dev -> main 으로 수정
loki config 수정
=> [#294] fix : logback & promtail 파일 수정
